//
// Created by ocean on 2023/1/6.
//

#ifndef CG_PROJECT_2022_FALL_INTEGRATOR_CUDA_CUH
#define CG_PROJECT_2022_FALL_INTEGRATOR_CUDA_CUH

#endif //CG_PROJECT_2022_FALL_INTEGRATOR_CUDA_CUH

#include "cuda.h"P